#!/usr/bin/env python3
"""PreToolUse hook for validating writes to .workflow files."""

import json
import os
import sys


def _tools_dir():
    hooks_dir = os.path.dirname(os.path.abspath(__file__))
    plugin_dir = os.path.dirname(hooks_dir)
    return os.path.join(plugin_dir, "tools")


def _load_validators():
    tools_dir = _tools_dir()
    if tools_dir not in sys.path:
        sys.path.insert(0, tools_dir)
    try:
        from workflow_lint import (
            validate_events,
            validate_milestones,
            validate_verify,
            validate_workflow,
        )
        return validate_workflow, validate_milestones, validate_verify, validate_events
    except ImportError:
        return None, None, None, None


def _is_workflow_file(file_path: str) -> bool:
    normalized = file_path.replace("\\", "/")
    # 支持绝对路径 (/.workflow/) 和相对路径 (.workflow/ 开头或 /.workflow/ 子串)
    if "/.workflow/" in normalized:
        return True
    # 相对路径: .workflow/xxx 或 subdir/.workflow/xxx
    parts = normalized.split("/")
    return ".workflow" in parts[:-1]  # .workflow 出现在目录部分


def _block(basename: str, errors: list[str]) -> None:
    print(
        f"\n⛔ [auto-pilot] Write to {basename} was blocked "
        f"({len(errors)} schema errors):",
        file=sys.stderr,
    )
    for i, err in enumerate(errors, 1):
        print(f"  {i}. {err}", file=sys.stderr)
    print("\n→ Fix the content to match tools/schemas/ and try again.", file=sys.stderr)
    sys.exit(2)


def _block_hook_payload_error(message: str) -> None:
    print(f"\n⛔ [auto-pilot] Hook input parse failed: {message}", file=sys.stderr)
    print("→ Blocking this write to avoid bypassing .workflow validation.", file=sys.stderr)
    sys.exit(2)


def _load_hook_payload():
    raw = sys.stdin.buffer.read()
    if not raw or not raw.strip():
        return None
    try:
        text = raw.decode("utf-8-sig")
    except UnicodeDecodeError as exc:
        _block_hook_payload_error(f"stdin is not valid UTF-8: {exc}")
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        _block_hook_payload_error(f"stdin is not valid JSON: {exc}")


def _simulate_edit(file_path: str, tool_input: dict) -> str | None:
    """读取原文件，应用 Edit 差异，返回编辑后的完整内容。失败返回 None。"""
    try:
        with open(file_path, "r", encoding="utf-8-sig") as f:
            original = f.read()
    except (OSError, UnicodeDecodeError):
        return None

    old_string = tool_input.get("old_string", "")
    new_string = tool_input.get("new_string", "")
    replace_all = tool_input.get("replace_all", False)

    if not old_string:
        return None

    if old_string not in original:
        return None

    if replace_all:
        return original.replace(old_string, new_string)
    else:
        return original.replace(old_string, new_string, 1)


def _check_approved_protection(file_path: str, new_data: dict, errors: list[str]) -> None:
    """H2: 禁止 AI 将 spec_approved / plan_approved 从非 true 改为 true。

    只有 workflow_confirm.py 工具可以设置这些字段。
    """
    if not isinstance(new_data, dict):
        return

    old_data = {}
    try:
        with open(file_path, "r", encoding="utf-8-sig") as f:
            old_data = json.load(f)
    except (OSError, json.JSONDecodeError, UnicodeDecodeError):
        # 文件不存在或无法读取时按首次写入处理，仍需阻止直接写 approved=true
        old_data = {}

    if not isinstance(old_data, dict):
        old_data = {}

    for field in ("spec_approved", "plan_approved"):
        old_val = old_data.get(field)
        new_val = new_data.get(field)
        if new_val is True and old_val is not True:
            errors.append(
                f"workflow.json {field} 不允许由 AI 直接设置为 true。"
                f"请使用 python tools/workflow_confirm.py 来确认。"
            )


def main() -> None:
    data = _load_hook_payload()
    if data is None:
        sys.exit(0)

    tool_name = data.get("tool_name", "")
    tool_input = data.get("tool_input", {})

    if tool_name not in ("Write", "Edit"):
        sys.exit(0)

    file_path = tool_input.get("file_path") or tool_input.get("path") or ""
    if not file_path or not _is_workflow_file(file_path):
        sys.exit(0)

    basename = os.path.basename(file_path)

    if tool_name == "Edit" and basename == "plan.md":
        print(
            "\n⛔ [auto-pilot] plan.md is generated by plan_sync.py export and "
            "should not be edited directly.\n"
            "Update milestones.json and then run: python tools/plan_sync.py export",
            file=sys.stderr,
        )
        sys.exit(2)

    if tool_name == "Edit":
        # 对 JSON/JSONL 文件，读取原文件并模拟应用差异后做校验
        if basename in ("workflow.json", "milestones.json", "verify.json", "events.jsonl"):
            content = _simulate_edit(file_path, tool_input)
            if content is None:
                # 无法模拟编辑（文件不存在等），放行但输出警告
                print(
                    f"\n⚠ [auto-pilot] 无法读取 {basename} 进行 Edit 校验，跳过验证。",
                    file=sys.stderr,
                )
                sys.exit(0)
        else:
            sys.exit(0)
    else:
        content = tool_input.get("content", "")
    if not content:
        sys.exit(0)

    errors: list[str] = []

    if basename in ("workflow.json", "milestones.json", "verify.json"):
        try:
            parsed = json.loads(content)
        except json.JSONDecodeError as exc:
            print(f"\n⛔ [auto-pilot] {basename} JSON parse failed: {exc}", file=sys.stderr)
            sys.exit(2)

        v_wf, v_ms, v_vf, _ = _load_validators()
        if basename == "workflow.json" and v_wf:
            v_wf(parsed, errors)
            # H2: approved 字段写保护 — 禁止 AI 将 approved 从非 true 改为 true
            _check_approved_protection(file_path, parsed, errors)
        elif basename == "milestones.json" and v_ms:
            v_ms(parsed, errors)
        elif basename == "verify.json" and v_vf:
            v_vf(parsed, errors)

    elif basename == "events.jsonl":
        lines = [line for line in content.strip().split("\n") if line.strip()]
        parsed_events = []
        for i, line in enumerate(lines, 1):
            try:
                parsed_events.append(json.loads(line))
            except json.JSONDecodeError as exc:
                errors.append(f"line {i} JSON parse failed: {exc}")
        if not errors:
            _, _, _, v_ev = _load_validators()
            if v_ev:
                v_ev(parsed_events, errors)

    elif basename == "plan.md":
        if "<!-- milestones_revision:" not in content:
            errors.append(
                "plan.md is missing milestones_revision metadata.\n"
                "    Generate it with `python tools/plan_sync.py export` instead of writing it by hand."
            )
    else:
        sys.exit(0)

    if errors:
        _block(basename, errors)

    sys.exit(0)


if __name__ == "__main__":
    main()
