#!/usr/bin/env python3
"""PreToolUse hook for validating writes to .workflow files."""

import json
import os
import sys


def _tools_dir():
    hooks_dir = os.path.dirname(os.path.abspath(__file__))
    plugin_dir = os.path.dirname(hooks_dir)
    return os.path.join(plugin_dir, "tools")


def _load_validators():
    tools_dir = _tools_dir()
    if tools_dir not in sys.path:
        sys.path.insert(0, tools_dir)
    try:
        from workflow_lint import (
            validate_events,
            validate_milestones,
            validate_verify,
            validate_workflow,
        )
        return validate_workflow, validate_milestones, validate_verify, validate_events
    except ImportError:
        return None, None, None, None


def _is_workflow_file(file_path: str) -> bool:
    normalized = file_path.replace("\\", "/")
    return "/.workflow/" in normalized


def _block(basename: str, errors: list[str]) -> None:
    print(
        f"\n⛔ [auto-pilot] Write to {basename} was blocked "
        f"({len(errors)} schema errors):",
        file=sys.stderr,
    )
    for i, err in enumerate(errors, 1):
        print(f"  {i}. {err}", file=sys.stderr)
    print("\n→ Fix the content to match tools/schemas/ and try again.", file=sys.stderr)
    sys.exit(2)


def _block_hook_payload_error(message: str) -> None:
    print(f"\n⛔ [auto-pilot] Hook input parse failed: {message}", file=sys.stderr)
    print("→ Blocking this write to avoid bypassing .workflow validation.", file=sys.stderr)
    sys.exit(2)


def _load_hook_payload():
    raw = sys.stdin.buffer.read()
    if not raw or not raw.strip():
        return None
    try:
        text = raw.decode("utf-8-sig")
    except UnicodeDecodeError as exc:
        _block_hook_payload_error(f"stdin is not valid UTF-8: {exc}")
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        _block_hook_payload_error(f"stdin is not valid JSON: {exc}")


def main() -> None:
    data = _load_hook_payload()
    if data is None:
        sys.exit(0)

    tool_name = data.get("tool_name", "")
    tool_input = data.get("tool_input", {})

    if tool_name not in ("Write", "Edit"):
        sys.exit(0)

    file_path = tool_input.get("file_path") or tool_input.get("path") or ""
    if not file_path or not _is_workflow_file(file_path):
        sys.exit(0)

    basename = os.path.basename(file_path)

    if tool_name == "Edit" and basename == "plan.md":
        print(
            "\n⛔ [auto-pilot] plan.md is generated by plan_sync.py export and "
            "should not be edited directly.\n"
            "Update milestones.json and then run: python tools/plan_sync.py export",
            file=sys.stderr,
        )
        sys.exit(2)

    if tool_name == "Edit":
        sys.exit(0)

    content = tool_input.get("content", "")
    if not content:
        sys.exit(0)

    errors: list[str] = []

    if basename in ("workflow.json", "milestones.json", "verify.json"):
        try:
            parsed = json.loads(content)
        except json.JSONDecodeError as exc:
            print(f"\n⛔ [auto-pilot] {basename} JSON parse failed: {exc}", file=sys.stderr)
            sys.exit(2)

        v_wf, v_ms, v_vf, _ = _load_validators()
        if basename == "workflow.json" and v_wf:
            v_wf(parsed, errors)
        elif basename == "milestones.json" and v_ms:
            v_ms(parsed, errors)
        elif basename == "verify.json" and v_vf:
            v_vf(parsed, errors)

    elif basename == "events.jsonl":
        lines = [line for line in content.strip().split("\n") if line.strip()]
        parsed_events = []
        for i, line in enumerate(lines, 1):
            try:
                parsed_events.append(json.loads(line))
            except json.JSONDecodeError as exc:
                errors.append(f"line {i} JSON parse failed: {exc}")
        if not errors:
            _, _, _, v_ev = _load_validators()
            if v_ev:
                v_ev(parsed_events, errors)

    elif basename == "plan.md":
        if "<!-- milestones_revision:" not in content:
            errors.append(
                "plan.md is missing milestones_revision metadata.\n"
                "    Generate it with `python tools/plan_sync.py export` instead of writing it by hand."
            )
    else:
        sys.exit(0)

    if errors:
        _block(basename, errors)

    sys.exit(0)


if __name__ == "__main__":
    main()
